insta/albums/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = "albums"

urlpatterns = [
    path('create/', views.CreateAlbumView.as_view(), name="create_album"),
    # path('detail/<album_slug>', views.DetailAlbumView.as_view(), name="album_detail"),
    path('detail/<slug:slug>', views.DetailAlbumView.as_view(), name="album_detail"),
    path('list', views.ListAlbumView.as_view(), name="album_list"),
    path('delete/<slug:slug>', views.DeleteAlbumView.as_view(), name="album_delete"),
    path('edit/<slug:slug>', views.UpdateAlbumView.as_view(), name="album_edit"),

]

insta/images/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = "images"

urlpatterns = [
    path('post/', views.CreateImageView.as_view(), name="create_image"),
    path('<int:pk>/', views.DetailImageView.as_view(), name="detail_image"),
    path('<int:pk>/edit/', views.UpdateImageView.as_view(), name="edit_image"),
    path('<int:pk>/delete/', views.DeleteImageView.as_view(), name="delete_image"),


]

insta/insta/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', views.index, name="home"),
    path('', views.HomePageView.as_view(), name="home"),
    path('accounts/', include("accounts.urls", namespace="accounts")),
    path('accounts/', include("django.contrib.auth.urls")),
    path('albums/', include("albums.urls", namespace="albums")),
    path('images/', include("images.urls", namespace="images")),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

insta/albums/models.py
import datetime

from django.db import models
from django.conf import settings
from django.utils.text import slugify
from django.utils import timezone
from django.urls import reverse

from django.contrib.auth import get_user_model
User = get_user_model()

# Create your models here.

class Album(models.Model):
    name = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(allow_unicode=True, unique=True)
    description = models.TextField(blank=True, default='')
    album_date = models.DateField(default=timezone.now)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        return super(Album, self).save(*args, **kwargs)


    def get_absolute_url(self):
        return reverse('albums:album_detail', kwargs={"slug": self.slug})


    # @classmethod
    # def album_count(Album):
    #     no_of_albums = Album.objects.count()
    #     if no_of_albums == 0:
    #         return



    class Meta:
        ordering = ['-album_date']

insta/albums/forms.py
from django import forms

from . import models

class AlbumForm(forms.ModelForm):

    class Meta:
        fields = ['name', 'description', 'album_date']
        model = models.Album

insta/albums/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import(LoginRequiredMixin)
from django.views.generic import (CreateView, UpdateView,
                                    DeleteView, ListView,
                                    DetailView)
from django.urls import reverse_lazy
from django.utils.text import slugify


# from braces.views import SelectRelatedMixin

from .forms import AlbumForm
from .models import Album
from images.models import Images

# Create your views here.


class CreateAlbumView(LoginRequiredMixin, CreateView):
    model = Album
    form_class = AlbumForm


class ListAlbumView(LoginRequiredMixin, ListView):
    model = Album

    def get_queryset_album_images(self):
        return image.album_images.count()


class UpdateAlbumView(LoginRequiredMixin, UpdateView):
    model = Album
    form_class = AlbumForm
    redirect_field_name = 'albums/album_detail.html'
    template_name = "albums/album_update_form.html"



class DeleteAlbumView(LoginRequiredMixin, DeleteView):
    model = Album
    success_url = reverse_lazy('albums:album_list')


class DetailAlbumView(LoginRequiredMixin, DetailView):
    model = Album
    # context_object_name = 'album_images'

    # def get_queryset(self):
    #     print (self.kwargs.get('slug'))
    #     a = Album.objects.get(slug=self.kwargs.get("slug"))
        # all_images = Images.objects.all()
        # return Images.objects.filter(album__name="{Album.name}")
        # return Images.objects.filter(album__name= a)

    # def get_object(self, queryset=None):
    #     slug = self.kwargs['slug']
    #     a_obj = Album.objects.get(slug=slug)
    #     try:
    #         i_obj = Images.objects.get(album=a_obj)
    #     except Images.DoesNotExist:
    #         d_obj = None
    #     except Images.MultipleObjectsReturned:
    #         return d_obj

    # def get_context_data(self, **kwargs):
    #     # xxx will be available in the template as the related objects
    #     context = super(DetailAlbumView, self).get_context_data(**kwargs)
    #     context['images_in_album'] = Images.objects.filter(album__name="{Album.name}")
    #     return context

insta/albums/templates/albums/album_confirm_delete.html
{% extends "base.html" %}

{% block content %}
<form class="delete_button" method="POST">
	{% csrf_token %}
	<input type="submit" value="Confirm Delete" class="btn btn-info">
	<a href="{% url 'albums:album_list' %}" class="btn btn-info">Cancel</a>
</form>

<h2 class="page_title">Are you sure you want to delete this album and all the images?</h2>

{% endblock %}

insta/albums/templates/albums/album_detail.html
{% extends "base.html"%}

{% block content %}

{% if user.is_authenticated %}
<a class="btn btn-primary icons" href="{% url 'albums:album_edit' slug=album.slug %}">
  <span class="fa fa-pencil"></span></a>
  <a class="btn btn-primary icons" href="{% url 'albums:album_delete' slug=album.slug %}">
    <span class="fa fa-remove"></span></a>
    <a class="btn btn-primary icons" href="{% url 'images:create_image'%}">
      <span class="fa fa-cloud-upload"></span></a>
      {% endif %}

  <div class="title_head">
    <h1 class="page_title">{{album.name}}</h1>
    <h4 class="image_description">{{album.description}}</h4>
    <h3 class="image_title_style image_count">{{album.album_images.count}} images</h3>
  </div>

  <div class="grid">
    {% for images in album.album_images.all%}
      {% include "images/_image.html" %}
    {% endfor %}
  </div>

{% endblock %}

insta/albums/templates/albums/album_form.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block content %}
<div class="container">
  <h2 class="page_title">Create Album</h2>
  <form method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button type="submit" class="btn btn-info">Create</button>
  </form>
</div>
{% endblock %}

insta/albums/templates/albums/album_list.html
{% extends "base.html"%}

{% block content %}
  {% if user.is_authenticated %}
    <a class="btn btn-primary icons" href="{% url 'albums:create_album'%}">
      <span class="	fa fa-plus-circle"></span></a>
  {% endif %}
  <h1 class="page_title">Albums</h1>

  {% for album in album_list %}
    <div class="box">
        {% for images in album.album_images.all|slice:"0:3"%}
          <a class="album_img first_img" href="{% url 'images:detail_image' pk=images.pk %}">
            <img class="img-fluid" src="{{images.image.url}}" alt="{{images.title}}">
          </a>
        {% endfor %}
    </div>

    <a class="image_title_style" href="{% url 'albums:album_detail' slug=album.slug %}"><strong>{{album.name}}</strong></a>
    <h3 class="image_title_style image_count">{{album.album_images.count}} images</h3>

  {% endfor %}

{% endblock %}

insta/albums/templates/albums/album_update_form.html
{% extends "base.html" %}
{% load bootstrap4 %}


{% block content %}
<h2 class="page_title">Edit Album</h2>
  <form method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button type="submit" class="btn btn-info">Update</button>
  </form>

{% endblock%}