insta/accounts/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = "accounts"

urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name="signup"),
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'),
        name="login"),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),

]

insta/albums/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = "albums"

urlpatterns = [
    path('create/', views.CreateAlbumView.as_view(), name="create_album"),
    # path('detail/<album_slug>', views.DetailAlbumView.as_view(), name="album_detail"),
    path('detail/<slug:slug>', views.DetailAlbumView.as_view(), name="album_detail"),
    path('list', views.ListAlbumView.as_view(), name="album_list"),
    path('delete/<slug:slug>', views.DeleteAlbumView.as_view(), name="album_delete"),
    path('edit/<slug:slug>', views.UpdateAlbumView.as_view(), name="album_edit"),

]

insta/images/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = "images"

urlpatterns = [
    path('post/', views.CreateImageView.as_view(), name="create_image"),
    path('<int:pk>/', views.DetailImageView.as_view(), name="detail_image"),
    path('<int:pk>/edit/', views.UpdateImageView.as_view(), name="edit_image"),
    path('<int:pk>/delete/', views.DeleteImageView.as_view(), name="delete_image"),


]

insta/insta/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', views.index, name="home"),
    path('', views.HomePageView.as_view(), name="home"),
    path('accounts/', include("accounts.urls", namespace="accounts")),
    path('accounts/', include("django.contrib.auth.urls")),
    path('albums/', include("albums.urls", namespace="albums")),
    path('images/', include("images.urls", namespace="images")),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

insta/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}

<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>MyInsta</title>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
    crossorigin="anonymous">

    <!-- Alternative to Bootstrap 3 Glyphicons -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
    rel="stylesheet">

    <script src="https://code.jquery.com/jquery-3.4.1.slim.js"
      integrity="sha256-BTlTdQO9/fascB1drekrDVkaKd9PkwBymMlHOiG+qLI="
      crossorigin="anonymous"></script>

    <!-- Masonry grid -->
    <!-- jQuery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <!-- imagesloaded. imagesloaded makes sure the images are not displayed
    until they are fully loaded -->
    <script src="https://unpkg.com/imagesloaded@4/imagesloaded.pkgd.min.js"></script>
    <!--load masonry -->
    <script src="https://unpkg.com/masonry-layout@4/dist/masonry.pkgd.min.js"></script>

    <link href="https://fonts.googleapis.com/css?family=Satisfy|Noto+Sans+SC&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/master.css' %}">



  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #d3e8ed;""
    role="navigation" id="navbar">
      <div class="container">
        <div class="navbar-nav align-items-center">
          <a class="navbar-brand mynav" href="{% url 'home' %}">MyInsta</a>
        </div>
        <div class="navbar-nav ml-auto">

          {% if user.is_authenticated %}
          <button class="navbar-toggler" type="button" data-toggle="collapse"
            data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false"
            aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav">
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'images:create_image'%}"
                  class="btn btn-simple">Upload</a>
              </li>

              <li class="nav-item active">
                <a class="nav-link" href="{% url 'albums:album_list'%}"
                  class="btn btn-simple">Album</a>
              </li>

              <li class="nav-item link">
                <a class="nav-item nav-link" href="{% url 'accounts:logout'%}"
                class="btn btn-simple">Log out</a>
              </li>
            </ul>
          </div>
          {% else %}
            <a class="nav-item nav-link" href="{% url 'accounts:login' %}"
              aria-label="Login">
              <span class="fa fa-user" aria-hidden="true"></span></a>
          {% endif %}



        </div>
      </div>
    </nav>

    <div class="container">
      {% block content%}
      {% endblock%}
    </div>


    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
      integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
      crossorigin="anonymous"></script>

    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
      integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
      crossorigin="anonymous"></script>


    <script>
      $(".grid").imagesLoaded(function() {
        $(".grid").masonry({
          itemSelector: ".grid-item"
        });
      });
    </script>




  </body>
</html>

insta/templates/index.html
{% extends "base.html" %}

{% block content %}
<div class="grid">
  {% for images in images_list %}
    {% if images.publish == 'PU' %}
      {% include "images/_image.html" %}
    {% endif %}
  {% endfor %}
</div>


{% endblock %}