insta/albums/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = "albums"

urlpatterns = [
    path('create/', views.CreateAlbumView.as_view(), name="create_album"),
    # path('detail/<album_slug>', views.DetailAlbumView.as_view(), name="album_detail"),
    path('detail/<slug:slug>', views.DetailAlbumView.as_view(), name="album_detail"),
    path('list', views.ListAlbumView.as_view(), name="album_list"),
    path('delete/<slug:slug>', views.DeleteAlbumView.as_view(), name="album_delete"),
    path('edit/<slug:slug>', views.UpdateAlbumView.as_view(), name="album_edit"),

]

insta/images/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = "images"

urlpatterns = [
    path('post/', views.CreateImageView.as_view(), name="create_image"),
    path('<int:pk>/', views.DetailImageView.as_view(), name="detail_image"),
    path('<int:pk>/edit/', views.UpdateImageView.as_view(), name="edit_image"),
    path('<int:pk>/delete/', views.DeleteImageView.as_view(), name="delete_image"),


]

insta/insta/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', views.index, name="home"),
    path('', views.HomePageView.as_view(), name="home"),
    path('accounts/', include("accounts.urls", namespace="accounts")),
    path('accounts/', include("django.contrib.auth.urls")),
    path('albums/', include("albums.urls", namespace="albums")),
    path('images/', include("images.urls", namespace="images")),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

insta/images/models.py
import datetime

from django import forms
from django.db import models
from django.conf import settings
from django.utils.text import slugify
from django.utils import timezone
from django.urls import reverse


from albums.models import Album
# from . import forms

from django.contrib.auth import get_user_model
User = get_user_model()

# Create your models here.
class Images(models.Model):
    title = models.CharField(max_length=100)
    image = models.ImageField(upload_to='images/')
    description = models.TextField(blank=True, default='')
    upload_date = models.DateField(default=timezone.now)
    album = models.ForeignKey(Album, related_name='album_images',
        on_delete=models.CASCADE)

    PRIVATE ='PR'
    PUBLIC = 'PU'

    PUBLISH_CHOICES = [
            (PRIVATE, 'Private'),
            (PUBLIC, 'Public'),]
    publish = models.CharField(max_length=7,
                        choices=PUBLISH_CHOICES,
                        default=PRIVATE)


    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('albums:album_detail', kwargs={"slug": slugify(self.album)})




    class Meta:
        ordering = ['-upload_date']

    # @property
    # def image_publish(self):
    #     return self.get_publish_display()

insta/images/forms.py
from django import forms

from . import models


class ImageForm(forms.ModelForm):
    # publish = forms.ChoiceField(widget=forms.RadioSelect(), required=True)

    class Meta:
        fields = ['album', 'title', 'image', 'description', 'publish']
        model = models.Images
    

insta/images/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import(LoginRequiredMixin)
from django.views.generic import (CreateView, UpdateView,
                                    DeleteView, ListView,
                                    DetailView)
from django.urls import reverse_lazy, reverse
from django.contrib import messages


from albums.models import Album
from .forms import ImageForm
from .models import Images

from django.contrib.auth import get_user_model
User = get_user_model()

# Create your views here.


class CreateImageView(LoginRequiredMixin, CreateView):
    model = Images
    form_class = ImageForm

    def form_valid(self, form):
        print(form.cleaned_data)
        return super().form_valid(form)


class ListImageView(LoginRequiredMixin, ListView):
    model = Images


class UpdateImageView(LoginRequiredMixin, UpdateView):
    model = Images
    form_class = ImageForm
    # fields = ['album', 'title', 'description']
    redirect_field_name = 'images/image_detail.html'
    template_name = 'images/images_update_form.html'


class DeleteImageView(LoginRequiredMixin, DeleteView):
    model = Images
    success_url = reverse_lazy('albums:album_list')

    # def get_success_url(self, **kwargs):
    #     return reverse('albums:album_detail', kwargs={"slug": self.kwargs.get("slug")})


class DetailImageView(LoginRequiredMixin, DetailView):
    model = Images

insta/images/templates/images/_image.html
<div class="grid-item">
    <a href="{% url 'images:detail_image' pk=images.pk %}">
      <img class="img-fluid" src="{{images.image.url}}" alt="{{images.title}}">
    </a>
    <h3 class="image_title_style"><strong>{{images.title}}</strong></h3>
    <h4 class="image_description">{{images.description}}</h4>
</div>

insta/images/templates/images/images_confirm_delete.html
{% extends "base.html" %}

{% block content %}

<form class="delete_button" method="POST">
	{% csrf_token %}
	<input type="submit" value="Confirm Delete" class="btn btn-info">
	<a href="{% url 'albums:album_list' %}" class="btn btn-info">Cancel</a>
</form>

<img class="img-fluid img_detail" src="{{images.image.url}}" alt="{{images.title}}">



{% endblock %}

insta/images/templates/images/images_detail.html
{% extends "base.html" %}
{% block content %}
{% if user.is_authenticated %}
<a class="btn btn-primary icons" href="{% url 'images:edit_image' pk=images.pk %}">
  <span class="fa fa-pencil"></span></a>
  <a class="btn btn-primary icons" href="{% url 'images:delete_image' pk=images.pk %}">
    <span class="fa fa-remove"></span></a>
    {% endif %}

  <h2 class="page_title">{{images.title}}</h2>
  <h3 class="image_title_style image_count">{{images.upload_date}}</h3>

  <img class="img-fluid img_detail" src="{{images.image.url}}" alt="{{images.title}}">


{% endblock %}

insta/images/templates/images/images_form.html
{% extends "base.html"%}
{% load bootstrap4 %}

{% block content %}
<div class="container">
  <h2 class="page_title">Upload Image</h2>
  <form method="post" enctype="multipart/form-data"
    action="{% url 'images:create_image'%}">
    {% csrf_token %}
    {% bootstrap_form form %}

    <button type="submit" class="btn btn-info">Upload</button>

  </form>
</div>
{% endblock %}

insta/images/templates/images/images_update_form.html
{% extends "base.html" %}

{% block content %}
<h2 class="page_title">Edit Image</h2>
  <form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit" class="btn btn-info">Update</button>
  </form>

{% endblock%}